### ISSUE TITLE
Revert back to original mitm module

### ISSUE THREAD

**Issue by gustavnikolaj** [unexpectedjs/unexpected-mitm#13]
@moll fixed the two issues that caused us to use @mwoc 's forked version of mitm. We should revert back as soon as the new mitm release is done.

I tested it by changing the require in lib/unexpectedMitm.js and npm linking the tip of mitm's master branch into unexpected-mitm. No tests were failing.

https://github.com/moll/node-mitm/pull/25

**Comment by papandreou** [comment]
Awesome, thanks for following through on that one.

**Comment by gustavnikolaj** [comment]
Fixed by @papandreou in https://github.com/unexpectedjs/unexpected-mitm/commit/31b4371d2fd6211a02c6f749bb5904fe72c16ba9

**Comment by gustavnikolaj** [comment]
I was just about to do the same, before I noticed that you already did the update. I was disappointed to see that we didn't have any failing tests when I first reverted the commit changing to the fork, before updating mitm. Should we add one retrospectively or is it just a waste of time now?

**Comment by papandreou** [comment]
I'm fairly sure the "original failing test" involved a client for a payment gateway. @mwoc?

**Comment by gustavnikolaj** [comment]
I guess we could create a rather simple test just asserting the core of the problem; that a connect event must be fired after the socket event...? :)

**Comment by papandreou** [comment]
It feels like something that should be covered by the mitm test suite.

**Comment by gustavnikolaj** [comment]
I expected to see something fail when swapping out the forked module and
running the test suite.
>
>
But you're right, it feels like it belongs in mitm now that it's fixed.

**Comment by moll** [comment]
It is: https://github.com/moll/node-mitm/blob/6b98f76858edbb66246c5bac3e2a0914968addcc/test/index_test.js#L445. ;-)
