### ISSUE TITLE
Breaks with Unexpected 10.9

### ISSUE THREAD

**Issue by papandreou** [unexpectedjs/unexpected-mitm#3]
Seems like the promise created in unexpected-mitm/lib/unexpectedMitm.js:693:39 is still pending when one of the tests ends.

My best idea is to complete the promisification of the library -- that'll probably make this error go away.

**Comment by alexjeffburke** [comment]
Fixed as of merge in b09c290e66eb26d59ad281e17e2eeb09ff2ffc94.
